controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    # joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster



position_controller:
  ros__parameters:
    joints:
      - upper_leg_joint
    interface_name: position
    state_interfaces:
      - position
    command_interfaces:
      - position

joint_state_broadcaster:
  ros__parameters:
    joints:
      - upper_leg_joint
    state_interfaces:
      - position

# to publish commands to the controller: ~/commands (input topic) [std_msgs::msg::Float64MultiArray]