controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # motor_position_controller:
    #   type: position_controllers/JointPositionController

forward_position_controller:
  ros__parameters:
    joints:
      - upper_leg_joint
    interface_name: position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - upper_leg_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
    
    action_monitor_rate: 50.0 #those are default values but how should i change them?
    state_publish_rate: 20.0 #default value

    allow_partial_joints_goal: true
    open_loop_control: true

    constraints:
      stoppped_velocity_tolerance: 0.01
      goal_time: 0.0
